name: 'CloudFormed'
description:
  'A Javascript Github Action that performs CloudFormed deployments.'
branding:
  icon: 'arrow-right'
  color: 'black'
inputs:
  url:
    description: 'The webhook URL to send the request to.'
    required: true
    default: ''
  json:
    description: 'The stringified JSON body to be sent, if any.'
    required: false
    default: '{}'
runs:
  using: 'node12'
  main: 'dist/index.js'
